### PR TITLE
Allow use of new avro_turf versions where child schemas are not liste…

### PR DESCRIPTION
**Pull request by dorner**
…d with the top level schemas

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Unit tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added a line in the CHANGELOG describing this change, under the UNRELEASED heading
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by iMacTia — COMMENTED** [review]
I had the chance to go through this today and it was an eye-opener!
I now understand how the schema generation works and how you managed to bring back secondary schema classes with these changes 🙌, thank you!

This also unlocks the version cap on `avro_turf`, which I'm sure will be useful in future 👌 

Can't wait to see this approved merged 🎉

**Comment by iMacTia** [comment]
@dorner did you notice that despite the changes, tests are still [not passing](https://github.com/flipp-oss/deimos/runs/5465990481?check_suite_focus=true) when executed with `avro_turf ~> 1.0`?

**Comment by dorner** [comment]
@iMacTia they have been fixed now! https://github.com/flipp-oss/deimos/pull/138

**Comment by iMacTia** [comment]
@dorner and it's passing on Ruby 3.0+ as well, fantastic 🎉 !

**Pull request merged**
