### PR TITLE
GUILD-618: Add bundle install to lint step

### PR DESCRIPTION
**Pull request by angad-singh**
# Pull Request Template

## Description

This PR fixes the lint step in the Github CI. It was failing because the `rubocop` gem was not available in the CI. I fixed it by running the `bundle install` command with the option `--with development` to install the development dependencies.

**The last 3 commits fix all the rubocop errors throughout the codebase. I used the autocorrect option while running rubocop and added `rubocop:disable` blocks for other errors.**

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
N/A

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added a line in the CHANGELOG describing this change, under the UNRELEASED heading
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dorner** [comment]
@angad-singh the tests may start working if you update to the latest avro_turf (>= 1). You can do this in the Gemfile (it won't affect the gemspec).

**Comment by angad-singh** [comment]
> @angad-singh the tests may start working if you update to the latest avro_turf (>= 1). You can do this in the Gemfile (it won't affect the gemspec).

@dorner Did you mean the files in `.gemfiles` like this? https://github.com/flipp-oss/deimos/blob/master/.gemfiles/avro_turf-0.gemfile

I changed it in this file https://github.com/flipp-oss/deimos/blob/master/deimos-ruby.gemspec which I am not so sure is the right way. (The tests didn't run due to an error in bundle install)

**Comment by angad-singh** [comment]
@dorner that didn't work :( Unless I did something wrong

**Comment by dorner** [comment]
Ack I forgot that the gemfiles actually are installing avro_turf :D Yes you'd need to put it in those `.gemfiles` files. My bad!

**Review by dorner — APPROVED** [review]

**Pull request merged**
